In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/Dataset_master.xlsx - Model Selection - Combined Cycl.csv')

In [ ]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [ ]:
data.head()

Ambient Temperature  Exhaust Vacuum  Ambient Pressure  Relative Humidity  \
0                14.96           41.76           1024.07              73.17   
1                25.18           62.96           1020.04              59.08   
2                 5.11           39.40           1012.16              92.14   
3                20.86           57.32           1010.24              76.64   
4                10.82           37.50           1009.23              96.62   

   electrical energy output  
0                    463.26  
1                    444.37  
2                    488.56  
3                    446.48  
4                    473.90

In [ ]:
data.isna().sum()

Ambient Temperature         0
Exhaust Vacuum              0
Ambient Pressure            0
Relative Humidity           0
electrical energy output    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


**Multiple Linear Regression**

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred=regressor.predict(X_test)

In [ ]:
print(y_pred)

[455.68 438.73 434.16 ... 482.17 435.42 458.76]


In [ ]:

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[455.68 455.27]
 [438.73 436.31]
 [434.16 440.68]
 ...
 [482.17 479.53]
 [435.42 435.76]
 [458.76 457.1 ]]


In [ ]:
from sklearn.metrics import r2_score
accuracy=r2_score(y_test,y_pred)
print(accuracy)

0.9301046431962188


**Polynomial Linear Regression**

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg=PolynomialFeatures(degree=4)
X_poly=poly_reg.fit_transform(X_train)


In [ ]:
regressor.fit(X_poly,y_train)


LinearRegression()

In [ ]:
y_pred2=regressor.predict(poly_reg.fit_transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[455.68 455.27]
 [438.73 436.31]
 [434.16 440.68]
 ...
 [482.17 479.53]
 [435.42 435.76]
 [458.76 457.1 ]]


In [ ]:
polyreg_accuracy2=r2_score(y_test,y_pred2)
polyreg_accuracy2

0.9431899329739429

**Random Forest Regression**

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf_regressor=RandomForestRegressor(n_estimators=10,random_state=21)
rf_regressor.fit(X_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=21)

In [ ]:
y_pred3=rf_regressor.predict(X_test)
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred3.reshape(len(y_pred3),1)),1))

[[455.27 454.31]
 [436.31 436.11]
 [440.68 433.18]
 ...
 [479.53 482.94]
 [435.76 433.39]
 [457.1  456.92]]


In [ ]:
rf_accuracy=r2_score(y_test,y_pred5)
rf_accuracy

0.9582380440682409

**Decision Tree Regression**

In [ ]:
from sklearn.tree import DecisionTreeRegressor
decision_reg=DecisionTreeRegressor(random_state=42)
decision_reg.fit(X_train,y_train)

DecisionTreeRegressor(random_state=42)

In [ ]:
y_pred4=decision_reg.predict(X_test)
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred4.reshape(len(y_pred4),1)),1))

[[455.27 455.57]
 [436.31 436.96]
 [440.68 431.73]
 ...
 [479.53 483.3 ]
 [435.76 429.28]
 [457.1  456.35]]


In [ ]:
dec_tree_accuracy=r2_score(y_test,y_pred)
dec_tree_accuracy

0.9301046431962188

**SVR Regression**

In [ ]:
y2 = y.reshape(len(y),1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y2, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train2 = sc_X.fit_transform(X_train2)
y_train2= sc_y.fit_transform(y_train2)

In [ ]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train2, y_train2)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
y_pred5 = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test2)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred5.reshape(len(y_pred),1), y_test2.reshape(len(y_test2),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


In [ ]:
from sklearn.metrics import r2_score
svm_reg_accuracy=r2_score(y_test2, y_pred5)

**Conclusion**
Random Forest Regression-0.9582380440682409
Polynomial Linear Regression-0.9431899329739429
Multiple Linear Regression-0.9301046431962188
